nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "php"
  volumes:
    - /opt:/opt

php:
  build: ./php 
  links:
    - "mysql"
  volumes:
    - /opt:/opt

mysql:
  build: ./mysql 
  volumes:
    - /opt/data/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456
